name: "File Encryptor"
description: "Encrypt or Decrypt a file on GitHub Event"
inputs:
  input-file-path:
    description: "Path of the file that needs to be encrypted"
    required: true
  encrypt-secret:
    description: "Secret used for encrypting the file content"
    required: true
  mode:
    description: "Mode can be either - encryption | decryption"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
